# Joint Group Velocity Controller ------------------------------------------------
arm_velocity_controller:
  type: velocity_controllers/JointGroupVelocityController
  joints:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
  gains:
    #!!These values are useable, but maybe not optimal
    ur5_shoulder_pan_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
    ur5_shoulder_lift_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
    ur5_elbow_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
    ur5_wrist_1_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
    ur5_wrist_2_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
    ur5_wrist_3_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
