# Joint Trajectory Controller - velocity based -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
arm_controller:
  type: velocity_controllers/JointTrajectoryController
  joints:
    - ur5_shoulder_pan_joint
    - ur5_shoulder_lift_joint
    - ur5_elbow_joint
    - ur5_wrist_1_joint
    - ur5_wrist_2_joint
    - ur5_wrist_3_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    ur5_shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
    ur5_shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
    ur5_elbow_joint: {trajectory: 0.1, goal: 0.1}
    ur5_wrist_1_joint: {trajectory: 0.1, goal: 0.1}
    ur5_wrist_2_joint: {trajectory: 0.1, goal: 0.1}
    ur5_wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  125
  action_monitor_rate: 10
  gains:
    #!!These values are useable, but maybe not optimal
    ur5_shoulder_pan_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
    ur5_shoulder_lift_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
    ur5_elbow_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
    ur5_wrist_1_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
    ur5_wrist_2_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
    ur5_wrist_3_joint: {p: 100.0,  i: 0.0, d: 0.1, i_clamp: 1}
