# Note: You MUST load these PID parameters for all joints that are using the
# PositionJointInterface, otherwise the arm + gripper will act like a giant
# parachute, counteracting gravity, and causing some of the wheels to lose
# contact with the ground, so the robot won't be able to properly navigate. See
# https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612
gazebo_ros_control:
  pid_gains:
    # these gains are used by the gazebo_ros_control plugin
    gripper_finger_joint:
      p: 100
      i: 10
      d: 0.001
      i_clamp: 1.0
      antiwindup: false
      publish_state: true
    # the following gains are used by the gazebo_mimic_joint plugin
    gripper_right_outer_knuckle_joint:
      p: 100
      i: 10
      d: 0.001
      i_clamp: 1.0
      antiwindup: false
      publish_state: true
    gripper_left_inner_knuckle_joint:
      p: 100
      i: 10
      d: 0.001
      i_clamp: 1.0
      antiwindup: false
      publish_state: true
    gripper_right_inner_knuckle_joint:
      p: 100
      i: 10
      d: 0.001
      i_clamp: 1.0
      antiwindup: false
      publish_state: true
    gripper_left_inner_finger_joint:
      p: 50
      i: 5
      d: 0.0001
      i_clamp: 0.5
      antiwindup: false
      publish_state: true
    gripper_right_inner_finger_joint:
      p: 50
      i: 5
      d: 0.0001
      i_clamp: 0.5
      antiwindup: false
      publish_state: true
