image: ros:noetic-ros-base

before_script:
  # Enable system-wide authentication for git cloning via https
  - '[ ! -z "$CI_DISPOSABLE_ENVIRONMENT" ] && echo -e "machine git.ni.dfki.de\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc'

  # Enable caching of APT packages (only works for packages.ubuntu.com and packages.ros.org)
  - echo "Acquire::http::Proxy \"http://apt-cache.ni.dfki:8000\";" | sudo tee /etc/apt/apt.conf.d/00proxy

build:
  stage: build
  tags:
    - docker
  script:
    - export CATKIN_WS=~/catkin_ws
    - export CATKIN_WS_SRC=${CATKIN_WS}/src
    - export CATKIN_PROJECT_DIR=$CATKIN_WS_SRC/mobipick

    # create a catkin workspace and clone all required ROS packages
    - mkdir -p $CATKIN_WS_SRC
    - cd $CATKIN_WS_SRC/
    - ln -s $CI_PROJECT_DIR $CATKIN_PROJECT_DIR   # outside CI, run this instead: git clone -b noetic git@git.ni.dfki.de:mobipick/mobipick.git

    - $CATKIN_PROJECT_DIR/install.sh

    # catkin_lint
    - cd $CATKIN_WS
    - source install/setup.bash
    - apt-get install -y python3-catkin-lint
    - cd $CATKIN_PROJECT_DIR
    - catkin_lint . --skip-pkg mobipick_moveit_config   # have to skip this package because of the missing warehouse_ros_mongo dependency

    # NOTE on testing: `catkin_make run_tests` will show the output of the tests
    # (gtest, nosetest, etc..) but always returns 0 (success) even if a test
    # fails. Running `catkin_test_results` aggregates all the results and returns
    # non-zero when a test fails (which notifies Gitlab CI that the build failed).
    - cd $CATKIN_WS
    - touch src/Universal_Robots_ROS_Driver/ur_robot_driver/CATKIN_IGNORE   # these tests now require a docker simulation of an UR running on the CI server: https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/209
    - catkin build --limit-status-rate 0.1 --no-notify --make-args tests
    - source devel/setup.bash
    - catkin run_tests --limit-status-rate 0.1 --no-notify
    - catkin_test_results
