image: ubuntu:bionic

before_script:
  # Enable system-wide authentication for git cloning via https
  - '[ ! -z "$CI_DISPOSABLE_ENVIRONMENT" ] && echo -e "machine git.ni.dfki.de\nlogin gitlab-ci-token\npassword ${CI_JOB_TOKEN}" > ~/.netrc'

build:
  stage: build
  tags:
    - docker
  script:
    - export LANG="en_US.UTF-8"
    - export LC_ALL=$LANG
    - export CI_ROS_DISTRO="melodic"
    - export CATKIN_WS=~/catkin_ws
    - export CATKIN_WS_SRC=${CATKIN_WS}/src
    - export CATKIN_PROJECT_DIR=$CATKIN_WS_SRC/mobipick

    # generate locale
    - apt-get update -qq
    - apt-get install locales
    - locale-gen $LANG

    # install tzdata non-interactively (tzdata is a requirement of the ROS packages below)
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get install -y tzdata
    - ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    - dpkg-reconfigure --frontend noninteractive tzdata

    # set up ROS repo
    # Install wget if not already installed
    - apt-get install -qq -y wget gnupg2
    - sh -c 'echo "deb http://packages.ros.org/ros/ubuntu bionic main" > /etc/apt/sources.list.d/ros-latest.list'
    - wget http://packages.ros.org/ros.key -O - | apt-key add -
    - apt-get update -qq
    - apt-get install -qq -y python-rosdep git build-essential cmake
    - apt-get install -qq -y ros-$CI_ROS_DISTRO-rosbash   # otherwise "source /opt/ros..." fails
    - apt-get install -qq -y python-catkin-tools
    - rosdep init
    - rosdep update

    # create a catkin workspace and clone all required ROS packages
    - mkdir -p $CATKIN_WS_SRC
    - cd $CATKIN_WS_SRC/
    - ln -s $CI_PROJECT_DIR $CATKIN_PROJECT_DIR   # outside CI, run this instead: git clone -b melodic git@git.ni.dfki.de:mobipick/mobipick.git
    - git clone -b master https://github.com/roboticsgroup/roboticsgroup_gazebo_plugins.git
    - git clone -b master https://github.com/JenniferBuehler/general-message-pkgs.git
    - git clone -b master https://github.com/JenniferBuehler/gazebo-pkgs.git
    - git clone -b calibration_devel https://github.com/fmauch/universal_robot.git fmauch_universal_robot
    - git clone -b master https://github.com/UniversalRobots/Universal_Robots_ROS_Driver.git Universal_Robots_ROS_Driver
    - git clone -b melodic-position-feedback https://git.ni.dfki.de/mobipick/robotiq.git robotiq
    - git clone -b master https://github.com/orbbec/ros_astra_camera.git astra_camera
    - git clone -b master https://git.ni.dfki.de/perception/astra_depth_filters.git
    - git clone -b 0.2.2 https://github.com/orbbec/ros_astra_launch.git astra_launch
    - git clone -b master https://git.ni.dfki.de/pbr_misc/pbr_tools.git

    # use rosdep to install all dependencies (including ROS itself)
    - rosdep install --from-paths ./ -i -y --rosdistro $CI_ROS_DISTRO --skip-keys=pico_flexx_driver

    # build all packages in the catkin workspace
    - source /opt/ros/${CI_ROS_DISTRO}/setup.bash
    - cd $CATKIN_WS
    - catkin init
    - catkin config --install --blacklist pico_flexx_driver --cmake-args -DCMAKE_BUILD_TYPE=RelWithDebugInfo
    - catkin build --limit-status-rate 0.1 --no-notify

    # catkin_lint
    - source install/setup.bash
    - apt-get install -y python-catkin-lint
    - cd $CATKIN_PROJECT_DIR
    - catkin_lint . --skip-pkg mobipick_moveit_config   # have to skip this package because of the missing warehouse_ros_mongo dependency

    # NOTE on testing: `catkin_make run_tests` will show the output of the tests
    # (gtest, nosetest, etc..) but always returns 0 (success) even if a test
    # fails. Running `catkin_test_results` aggregates all the results and returns
    # non-zero when a test fails (which notifies Gitlab CI that the build failed).
    - cd $CATKIN_WS
    - touch src/Universal_Robots_ROS_Driver/ur_robot_driver/CATKIN_IGNORE   # these tests now require a docker simulation of an UR running on the CI server: https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/209
    - catkin build --limit-status-rate 0.1 --no-notify --make-args tests
    - source devel/setup.bash
    - catkin run_tests --limit-status-rate 0.1 --no-notify
    - catkin_test_results
