#ifndef MOBIPICK_PICK_N_PLACE_FAKE_OBJECT_RECOGNITION_H
#define MOBIPICK_PICK_N_PLACE_FAKE_OBJECT_RECOGNITION_H

enum ObjectID {TABLE = 100, COKE_CAN = 101};

#endif //MOBIPICK_PICK_N_PLACE_FAKE_OBJECT_RECOGNITION_H
