# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  

# Position Controllers ---------------------------------------
gripper_controller:
  type: position_controllers/JointPositionController
  joint: finger_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
#gripper_right_controller:
#  type: position_controllers/JointPositionController
#  joint: right_outer_knuckle_joint
#  pid: {p: 100.0, i: 0.01, d: 10.0}
