# Position Controllers ---------------------------------------
gripper_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - gripper_finger_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.05
    gripper_finger_joint: {trajectory: 0.1, goal: 0.02}
  stop_trajectory_duration: 0.5
  state_publish_rate:  125
  action_monitor_rate: 10
