# Position Controllers ---------------------------------------
gripper_controller:
  type: position_controllers/JointPositionController
  joint: gripper_finger_joint
#  pid: {p: 100.0, i: 0.01, d: 10.0}
