<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="table">

  <xacro:property name="width"               value="1.40" />
  <xacro:property name="depth"               value="0.70" />
  <xacro:property name="height"              value="0.72" />
  <xacro:property name="leg_radius"          value="0.02" />
  <xacro:property name="table_top_thickness" value="0.05" />
  <xacro:property name="x"                   value="0.0" />
  <xacro:property name="y"                   value="0.0" />
  <xacro:property name="z"                   value="0.0" />

  <xacro:property name="barrier_width"       value="${width + 2*leg_radius}" />
  <xacro:property name="barrier_depth"       value="0.01" />
  <xacro:property name="barrier_height"      value="0.05" />

  <xacro:include filename="$(find mobipick_gazebo)/urdf/include/table.urdf.xacro" />
  <xacro:table height="${height}" width="${width}" depth="${depth}" leg_radius="${leg_radius}" table_top_thickness="${table_top_thickness}" x="${x}" y="${y}" z="${z}" />

  <joint name="barrier_joint" type="fixed" >
    <parent link="table_top_link" />
    <origin xyz="${x} ${y + depth/2 + leg_radius + barrier_depth/2} 0.19" rpy="0 0 0" />
    <child link="barrier_link" />
  </joint>
  <link name="barrier_link">
    <xacro:box_inertial x="${barrier_width}" y="${barrier_depth}" z="${barrier_height}" mass="0.2">
      <origin xyz="0 0 0" />
    </xacro:box_inertial>
    <visual>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${barrier_width} ${barrier_depth} ${barrier_height}" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" />
      <geometry>
        <box size="${barrier_width} ${barrier_depth} ${barrier_height}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="barrier_link">
    <material>Gazebo/Black</material>
  </gazebo>
</robot>
