<robot  xmlns:xacro="http://ros.org/wiki/xacro" name="power_drill_model">
  <xacro:include filename="$(find mobipick_description)/urdf/common_properties.urdf.xacro" />

  <xacro:property name="mass" value="1.284" />

  <link name="power_drill">
    <!-- <xacro:cylinder_inertial radius="${radius}" length="${height}" mass="${mass}">
      <origin xyz="0 0 ${height/2}" rpy="0 0 0" />
    </xacro:cylinder_inertial> -->
    <inertial>
      <origin xyz="-0.03071469 0.02435085 0.02356763" rpy="0 0 0" />
      <mass value="${mass}" />
      <inertia
        ixx="${mass * 0.003988511412844956}"
        ixy="${mass * 0.0004112614213275305}"
        ixz="${mass * 0.00003166287680811595}"
        iyy="${mass * 0.0016270423052260282}"
        iyz="${mass * 0.0000807201704454}"
        izz="${mass * 0.00534355593909}" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://mobipick_gazebo/meshes/power_drill.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://mobipick_gazebo/meshes/power_drill.dae" />
      </geometry>
    </collision>
  </link>
</robot>
