<robot  xmlns:xacro="http://ros.org/wiki/xacro" name="powerdrill_with_grip_model">
  <xacro:include filename="$(find mobipick_description)/urdf/common_properties.urdf.xacro" />

  <xacro:property name="mass" value="0.500" />

  <link name="powerdrill_with_grip">
    <!-- <xacro:cylinder_inertial radius="${radius}" length="${height}" mass="${mass}">
      <origin xyz="0 0 ${height/2}" rpy="0 0 0" />
    </xacro:cylinder_inertial> -->
    <inertial>
      <origin xyz="0.01524081 -0.01376334 0.00190586" rpy="0 0 0" />
      <mass value="${mass}" />
      <inertia
        ixx="${mass * 0.003988511412844956}"
        ixy="${mass * -0.0004112614213275305}"
        ixz="${mass * -0.00003166287680811595}"
        iyy="${mass * 0.0016270423052260282}"
        iyz="${mass * 0.0000807201704454}"
        izz="${mass * 0.00534355593909}" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${pi} 0 0" />
      <geometry>
        <mesh filename="package://mobipick_gazebo/meshes/powerdrill_with_grip.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${pi} 0 0" />
      <geometry>
        <mesh filename="package://mobipick_gazebo/meshes/powerdrill_with_grip.dae" />
      </geometry>
    </collision>
  </link>
</robot>
