# Picking parameters

# the list of names of the gripper joint
gripper_joint_names:
    - mobipick/gripper_finger_joint

# the distance in meters that the gripper should close to grasp objects by default
# this value can be override by "distance_gripper_close_per_obj" param
#   which is a dictionary with object_class vs custom values per object
gripper_close:
    - 0.0 # close gripper completely

# the distance in meters that the gripper should have when opening by default
# this value can be override by "distance_gripper_open_per_obj" param
#   which is a dictionary with object_class vs custom values per object
gripper_open:
    - 0.14

# the list of max torque values to apply while closing the gripper around the object
# for the Robotiq 2F gripper on Mobipick: min: 30.0, max: 100.0
gripper_joint_efforts:
    - 100.0

# The estimated probability of success for this grasp, or some other measure of how 'good' it is.
# for now we set all grasp quality to 1.0, later on this value needs to be taken from the grasp planner
grasp_quality: 1.0

# the maximum contact force to use while grasping (<=0 to disable)
max_contact_force: 1.0

# The approach direction to take before picking an object
# values are expressed w.r.t end_effector reference frame
pre_grasp_approach:
    min_dist: 0.08
    desired: 0.25
    axis: [1.0, 0.0, 0.0] # side grasp, approach in "x" axis to object

# The retreat direction to take after a grasp has been completed (object is attached)
post_grasp_retreat:
    frame_id: 'mobipick/odom'
    min_dist: 0.1
    desired: 0.15
    axis: [0.0, 0.0, 1.0] # lift object up in "z" direction
