<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find mobipick_description)/urdf/common_properties.urdf.xacro" />
  <xacro:include filename="$(find mobipick_description)/urdf/mir_100/mir_100.transmission.xacro" />
  <xacro:include filename="$(find mobipick_description)/urdf/mir_100/mir_100.gazebo.xacro" />

  <xacro:property name="deg_to_rad" value="0.017453293" />

  <xacro:property name="mir_100_base_mass" value="58.0" />

  <xacro:property name="mir_100_act_wheel_radius" value="0.0625" />
  <xacro:property name="mir_100_act_wheel_width" value="0.032" />
  <xacro:property name="mir_100_act_wheel_mass" value="1.0" />
  <xacro:property name="mir_100_act_wheel_dx" value="0.037646" />
  <xacro:property name="mir_100_act_wheel_dy" value="0.222604" />

  <xacro:property name="mir_100_caster_wheel_radius" value="${mir_100_act_wheel_radius}" />
  <xacro:property name="mir_100_caster_wheel_width" value="${mir_100_act_wheel_width}" />
  <xacro:property name="mir_100_caster_wheel_mass" value="${mir_100_act_wheel_mass}" />
  <xacro:property name="mir_100_caster_wheel_dx" value="-0.0382" />
  <xacro:property name="mir_100_caster_wheel_dy" value="0" />
  <xacro:property name="mir_100_caster_wheel_dz" value="-0.094" />
  <xacro:property name="mir_100_front_caster_wheel_base_dx" value="0.341346" />
  <xacro:property name="mir_100_back_caster_wheel_base_dx" value="-0.270154" />
  <xacro:property name="mir_100_caster_wheel_base_dy" value="0.203" />
  <xacro:property name="mir_100_caster_wheel_base_dz" value="${mir_100_caster_wheel_radius-mir_100_caster_wheel_dz}" />

  <xacro:macro name="actuated_wheel_link" params="prefix locationprefix">
    <link name="${prefix}${locationprefix}_act_wheel">
      <xacro:cylinder_inertial mass="${mir_100_act_wheel_mass}" radius="${mir_100_act_wheel_radius}" length="${mir_100_act_wheel_width}">
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/mir_100/visual/actuated_wheel.stl" />
        </geometry>
        <xacro:insert_block name="material_dark_grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/mir_100/collision/actuated_wheel.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}${locationprefix}_act_wheel">
      <material>Gazebo/DarkGrey</material>
    </gazebo>
  </xacro:macro>


  <xacro:macro name="caster_wheel_links" params="prefix locationprefix">
    <link name="${prefix}${locationprefix}_caster_wheel_base">
      <inertial>
        <!-- <origin xyz="0 0 -0.042500000044" rpy="${0.5 * pi} ${24 * deg_to_rad} ${1.5 * pi}" /> -->
        <origin xyz="0 0 -0.042500000044" rpy="${24 * deg_to_rad} 0 ${0.5 * pi} " />
        <mass value="0.3097539019" />
        <inertia
          ixx="0.0005844517978"
          ixy="0"
          ixz="0"
          iyy="0.00052872551237"
          iyz="0"
          izz="0.00017923555074" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/mir_100/visual/caster_wheel_base.stl" />
        </geometry>
        <xacro:insert_block name="material_silver" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/mir_100/collision/caster_wheel_base.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}${locationprefix}_caster_wheel_base">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}${locationprefix}_caster_wheel">
      <xacro:cylinder_inertial mass="${mir_100_caster_wheel_mass}" radius="${mir_100_caster_wheel_radius}" length="${mir_100_caster_wheel_width}">
        <origin xyz="0 0 0" rpy="${0.5 * pi} 0 0" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/mir_100/visual/caster_wheel.stl" />
        </geometry>
        <xacro:insert_block name="material_dark_grey" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/mir_100/collision/caster_wheel.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}${locationprefix}_caster_wheel">
      <material>Gazebo/DarkGrey</material>
    </gazebo>
  </xacro:macro>


  <xacro:macro name="actuated_wheel_joint" params="prefix locationprefix locationright">
    <joint name="${prefix}${locationprefix}_wheel_joint" type="continuous">
      <origin xyz="0.0 ${-mir_100_act_wheel_dy * locationright} ${mir_100_act_wheel_radius}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}${locationprefix}_act_wheel" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="20.0" />
    </joint>
  </xacro:macro>


  <xacro:macro name="front_caster_wheel_joints" params="prefix locationprefix locationright">
    <joint name="${prefix}base_link_front_${locationprefix}_wheel_base_joint" type="continuous">
      <origin xyz="${mir_100_front_caster_wheel_base_dx} ${-mir_100_caster_wheel_base_dy * locationright} ${mir_100_caster_wheel_base_dz}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}front_${locationprefix}_caster_wheel_base" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.01" friction="0.0"/>
    </joint>
    <joint name="${prefix}base_link_front_${locationprefix}_wheel_joint" type="continuous">
      <origin xyz="${mir_100_caster_wheel_dx} ${-mir_100_caster_wheel_dy * locationright} ${mir_100_caster_wheel_dz}" rpy="0 0 0" />
      <parent link="${prefix}front_${locationprefix}_caster_wheel_base" />
      <child link="${prefix}front_${locationprefix}_caster_wheel" />
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>

  <xacro:macro name="back_caster_wheel_joints" params="prefix locationprefix locationright">
    <joint name="${prefix}base_link_back_${locationprefix}_wheel_base_joint" type="continuous">
      <origin xyz="${mir_100_back_caster_wheel_base_dx} ${-mir_100_caster_wheel_base_dy * locationright} ${mir_100_caster_wheel_base_dz}" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}back_${locationprefix}_caster_wheel_base" />
      <axis xyz="0 0 1" />
      <dynamics damping="0.01" friction="0.0"/>
    </joint>
    <joint name="${prefix}base_link_back_${locationprefix}_wheel_joint" type="continuous">
      <origin xyz="${mir_100_caster_wheel_dx} ${-mir_100_caster_wheel_dy * locationright} ${mir_100_caster_wheel_dz}" rpy="0 0 0" />
      <parent link="${prefix}back_${locationprefix}_caster_wheel_base" />
      <child link="${prefix}back_${locationprefix}_caster_wheel" />
      <axis xyz="0 1 0" />
    </joint>
  </xacro:macro>

  <xacro:macro name="mir_100" params="prefix">

    <link name="${prefix}base_footprint" />

    <joint name="${prefix}base_joint" type="fixed">
      <parent link="${prefix}base_footprint" />
      <child link="${prefix}base_link" />
      <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="${prefix}base_link">
      <xacro:box_inertial mass="${mir_100_base_mass}" x="0.9" y="0.58" z="0.3">
        <origin xyz="${mir_100_act_wheel_dx} 0 0.20" rpy="0 0 0" />
      </xacro:box_inertial>
      <visual>
        <origin xyz="${mir_100_act_wheel_dx} 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/mir_100/visual/mir_100_base.stl" />
        </geometry>
        <xacro:insert_block name="material_white" />
      </visual>
      <collision>
        <origin xyz="${mir_100_act_wheel_dx} 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/mir_100/collision/mir_100_base.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}base_link">
      <material>Gazebo/White</material>
    </gazebo>

    <xacro:actuated_wheel_link prefix="${prefix}" locationprefix="left"/>
    <xacro:actuated_wheel_link prefix="${prefix}" locationprefix="right"/>
    <xacro:caster_wheel_links prefix="${prefix}" locationprefix="front_left"/>
    <xacro:caster_wheel_links prefix="${prefix}" locationprefix="front_right"/>
    <xacro:caster_wheel_links prefix="${prefix}" locationprefix="back_left"/>
    <xacro:caster_wheel_links prefix="${prefix}" locationprefix="back_right"/>

    <xacro:actuated_wheel_joint prefix="${prefix}" locationprefix="left" locationright="-1"/>
    <xacro:actuated_wheel_joint prefix="${prefix}" locationprefix="right" locationright="1"/>
    <xacro:front_caster_wheel_joints prefix="${prefix}" locationprefix="left" locationright="-1"/>
    <xacro:front_caster_wheel_joints prefix="${prefix}" locationprefix="right" locationright="1"/>
    <xacro:back_caster_wheel_joints prefix="${prefix}" locationprefix="left" locationright="-1"/>
    <xacro:back_caster_wheel_joints prefix="${prefix}" locationprefix="right" locationright="1"/>


    <joint name="${prefix}base_link_surface_joint" type="fixed">
      <origin xyz="${mir_100_act_wheel_dx} 0 0.352" rpy="0 0 0" />
      <parent link="${prefix}base_link" />
      <child link="${prefix}surface" />
      <axis xyz="0 0 1" />
    </joint>

    <link name="${prefix}surface"/>

    <xacro:mir_100_wheel_transmissions prefix="${prefix}"/>

    <!-- disabled, because it doesn't make a difference in Gazebo: -->
    <!-- <xacro:set_all_wheel_frictions prefix="${prefix}"/> -->
  </xacro:macro>
</robot>
