# Note: You MUST load these PID parameters for all joints that are using the
# PositionJointInterface, otherwise the arm + gripper will act like a giant
# parachute, counteracting gravity, and causing some of the wheels to lose
# contact with the ground, so the robot won't be able to properly navigate. See
# https://github.com/ros-simulation/gazebo_ros_pkgs/issues/612
gazebo_ros_control:
  pid_gains:
    ur5_shoulder_pan_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
    ur5_shoulder_lift_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
    ur5_elbow_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
    ur5_wrist_1_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
    ur5_wrist_2_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
    ur5_wrist_3_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
