# Publish all joint states -----------------------------------
gazebo_ros_control:
  pid_gains:
    ur5_shoulder_pan_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
    ur5_shoulder_lift_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
    ur5_elbow_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
    ur5_wrist_1_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
    ur5_wrist_2_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
    ur5_wrist_3_joint:
      p: 70.0
      i: 1.50 
      d: 5.00
      i_clamp: 2
      publish_state: true
