TrajectoryPlannerROS:
  # Robot configuration
  acc_lim_x: 0.1
  acc_lim_y: 0
  acc_lim_theta: 0.2
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_vel_theta: 0.2
  min_vel_theta: -0.2
  min_in_place_vel_theta: 0.2
  escape_vel: -0.2
  holonomic_robot: false

  # Goal tolerance
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.3
  latch_xy_goal_tolerance: true

  # Forward simulaton parameters
  sim_time: 1
  sim_granularity: 0.1
  angular_sim_granularity: 0.04
  vx_samples: 3
  vtheta_samples: 20
  controller_frequency: 5

  # Trajectory scoring parameters
  meter_scoring: true
  pdist_scale: 2.2 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.1
  heading_lookahead: 0.325
  heading_scoring: true
  heading_scoring_timestep: 0.8
  dwa: true
  publish_cost_grid: false
  global_frame_id: map

  # Oscillation prevention parameter
  oscillation_reset_dist: 0.05

  # Global plan parameters
  prune_plan: true
