local_costmap:
    #global_frame: /map #odom
    #static_map: true #false
    #rolling_window: false #true
    global_frame: odom_comb
    static_map: false
    rolling_window: true
    width: 50.0
    height: 50.0
    origin_x: 0.0
    origin_y: 0.0
    plugins: 
        - {name: obstacles,  type: "costmap_2d::VoxelLayer" }
        - {name: virtual_walls_map, type: "costmap_2d::StaticLayer" }
        - {name: inflation,  type: "costmap_2d::InflationLayer" }
