robot_base_frame: base_link
transform_tolerance: 0.5
update_frequency: 5.0
publish_frequency: 1.0
#footprint: [[4.0,0.35],[-4.0,0.35],[-4.0,-0.35],[4.0,-0.35]]
footprint: [[4.2,0.15],[1.1,0.15],[1.1,0.35],[-1.1,0.35],[-1.1,0.15],[-3.6,0.15],[-3.6,-0.15],[-1.1,-0.15],[-1.1,-0.35],[1.1,-0.35],[1.1,-0.15],[4.2,-0.15]]
#footprint: [[1.0,0.35],[-1.0,0.35],[-1.0,-0.35],[1.0,-0.35]]
footprint_padding: 0.1
obstacle_range: 10.0
raytrace_range: 20.0
resolution: 0.1
z_resolution: 0.3
z_voxels: 5
#mark_threshold: 1
publish_voxel_map: true
static_map:
  map_topic: /map
  first_map_only: true
obstacles:
  observation_sources: scan_marking scan_clearing
  scan_marking:  {topic: scan_rep117, data_type: LaserScan, clearing: false, marking: true, inf_is_valid: false}
  scan_clearing: {topic: scan_rep117, data_type: LaserScan, clearing: true, marking: false, inf_is_valid: true}
virtual_walls_map:
  map_topic: /virtual_walls/map
  first_map_only: true
  use_maximum: true
inflation:
  cost_scaling_factor:  1.2  # Exponential rate at which the obstacle cost drops off (default: 10). Must be chosen so that the cost value is > 0 at robot's circumscribed radius.
  inflation_radius:     5.0  # Max. distance from an obstacle at which costs are incurred for planning paths. Must be > robot's circumscribed radius.
