global_costmap:
    global_frame: /map
    static_map: true
    update_frequency: 1.0
    publish_frequency: 1.0
    plugins: 
        - {name: navigation_map, type: "costmap_2d::StaticLayer" }
        - {name: obstacles,  type: "costmap_2d::VoxelLayer" }
        - {name: virtual_walls_map, type: "costmap_2d::StaticLayer" }
        - {name: inflation,  type: "costmap_2d::InflationLayer" }
