base_local_planner: eband_local_planner/EBandPlannerROS
EBandPlannerROS:
  # Robot configuration
  max_vel_lin: 0.8                                  # choose slightly less than the base's capability
  min_vel_lin: 0.1                                  # this is the min trans velocity when there is negligible rotational velocity
  trans_stopped_vel: 0.03

  max_vel_th: 1.0                                   # choose slightly less than the base's capability
  min_vel_th: 0.1                                   # this is the min angular velocity when there is negligible translational velocity
  rot_stopped_vel: 0.1

  min_in_place_vel_th: 0.1                          # Minimum in-place angular velocity
  in_place_trans_vel: 0.0                           # Minimum in place linear velocity

  max_acceleration: 1.5                             # Maximum allowable acceleration
  max_translational_acceleration: 1.5               # Maximum linear acceleration
  max_rotational_acceleration: 2.0                  # Maximum angular acceleration

  # Goal tolerance
  yaw_goal_tolerance: 0.03                          # yaw_goal_tolerance > (sim_time * min_rot_vel) / 2 (from Navigation Tuning Guide)
  xy_goal_tolerance: 0.08                           # xy_goal_tolerance  > (sim_time * min_vel_x)   / 2

  # Elastic Band Parameters
  eband_min_relative_overlap: 0.7                   # Min distance that denotes connectivity between consecutive bubbles
  eband_tiny_bubble_distance: 0.01                  # Bubble geometric bound regarding tiny bubble distance
  eband_tiny_bubble_expansion: 0.01                 # Bubble geometric bound regarding tiny bubble expansion
  eband_internal_force_gain: 1.0                    # Force gain of forces between consecutive bubbles that tend to stretch the elastic band
  eband_external_force_gain: 2.0                    # Force gain of forces that tend to move the bubbles away from obstacles
  num_iterations_eband_optimization: 3              # Number of iterations for eband optimization
  eband_equilibrium_approx_max_recursion_depth: 4   # Number of iterations for reaching the equilibrium between internal and external forces
  eband_equilibrium_relative_overshoot: 0.75        # Maximum relative equlibrium overshoot
  eband_significant_force_lower_bound: 0.15         # Minimum magnitude of force that is considered significant and used in the calculations
  costmap_weight: 10.0                              # Costmap weight factor used in the calculation of distance to obstacles

  # Trajectory Controller Parameters
  k_prop: 4.0                                       # Proportional gain of the PID controller
  k_damp: 3.5                                       # Damping gain of the PID controller
  Ctrl_Rate: 10.0                                   # Control rate
  virtual_mass: 0.75                                # Virtual mass
  rotation_correction_threshold: 0.5                # Rotation correction threshold
  differential_drive: True                          # Denotes whether to use the differential drive mode
  bubble_velocity_multiplier: 2.0                   # Multiplier of bubble radius
  rotation_threshold_multiplier: 1.0                # Multiplier of rotation threshold
  disallow_hysteresis: False                        # Determines whether to try getting closer to the goal, in case of going past the tolerance
