base_global_planner: SBPLLatticePlanner
#base_global_planner: global_planner/GlobalPlanner
#base_local_planner: base_local_planner/TrajectoryPlannerROS
base_local_planner: teb_local_planner/TebLocalPlannerROS
#base_local_planner: dwa_local_planner/DWAPlannerROS
