base_local_planner: teb_local_planner/TebLocalPlannerROS
TebLocalPlannerROS:
  # Robot configuration
  acc_lim_x: 1.5
  acc_lim_theta: 2.0
  max_vel_x: 0.8
  max_vel_x_backwards: 0.2
  max_vel_theta: 1.0

  footprint_model: 
    type: "polygon"
    vertices: [ [4.0,-0.35], [4.0,+0.35],[-4.0,+0.35], [-4.0,+0.35] ]

  # Goal tolerance
  xy_goal_tolerance: 0.03
  yaw_goal_tolerance: 0.08
  free_goal_vel: false

  # Trajectory Configuration Parameter
  dt_ref: 0.1 # 
  dt_hysteresis: 0.05
  min_samples: 3
  global_plan_overwrite_orientation: false
  global_plan_viapoint_sep:  0.1 #-0.1 # diabled
  max_global_plan_lookahead_dist: 1.0
  force_reinit_new_goal_dist: 1.0
  feasibility_check_no_poses: 4
  publish_feedback: false
  shrink_horizon_backup: true

  # Obstacle Parameters
  min_obstacle_dist: 0.5
  costmap_obstacles_behind_robot_dist: 1.0
  obstacle_poses_affected: 30
  inflation_dist:  0.6
  costmap_converter_plugin: ""
  costmap_converter_spin_thread: true
  costmap_converter_rate: 5.0

  # Optimization Parameters
  no_inner_iterations: 5
  no_outer_iterations: 4
  penalty_epsilon: 0.1
  weight_max_vel_x: 2.0
  weight_max_vel_theta: 1.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_theta: 1.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 1.0
  weight_kinematics_turning_radius: 0.0
  weight_optimaltime: 0.1
  weight_obstacle: 50.0
  weight_viapoint: 10.0
  weight_inflation: 0.1

  # Parallel Planning in distinctive Topologies
  enable_homotopy_class_planning: true
  enable_multithreading: true
  max_number_classes: 4
  selection_cost_hysteresis: 1.0
  selection_obst_cost_scale: 100.0
  selection_viapoint_cost_scale: 100.0
  selection_alternative_time_cost: false
  roadmap_graph_no_samples: 15
  roadmap_graph_area_width: 6
  h_signature_prescaler: 1.0
  h_signature_threshold: 0.1
  obstacle_heading_threshold: 1.0
  visualize_hc_graph: false
  viapoints_all_candidates: true

  odom_topic: odom
  map_frame: /map
