<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       name="mobipick">

  <xacro:arg name="robot" default="mobipick-hb" />      <!-- can be "mobipick-hb" or "mobipick-os" -->
  <xacro:property name="robot" value="$(arg robot)" />  <!-- necessary because args cannot be accessed inside ${} expressions -->

  <!-- ############# MIR100 BASE ############## -->
  <xacro:include filename="$(find mobipick_description)/urdf/mir_100/mir_100_v1.urdf.xacro" />

  <xacro:mir_100 prefix=""/>

  <!-- ############## STRUCTURE ############### -->
  <xacro:include filename="$(find mobipick_description)/urdf/structure/mobipick_structure.urdf.xacro" />

  <joint name="mir_struct_joint" type="fixed">
    <parent link="surface" />
    <child link = "structure_part_down" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
  </joint>

  <xacro:if value="${robot == 'mobipick-hb'}">
    <xacro:structure prefix="structure_" height="0.058" variant="v1" />
  </xacro:if>
  <xacro:if value="${robot == 'mobipick-os'}">
    <xacro:structure prefix="structure_" height="0.058" variant="v2" />
  </xacro:if>

  <!-- ############### UR5 ARM ################ -->
  <xacro:include filename="$(find mobipick_description)/urdf/ur5/ur5.urdf.xacro" />

  <joint name="struct_ur5_joint" type="fixed">
    <parent link="structure_pedestal_surface" />
    <child link = "ur5_base_link" />
    <origin xyz="0.0 0.0 0.0025" rpy="0.0 0.0 0.0" />
  </joint>

  <xacro:ur5_robot prefix="ur5_" joint_limited="true"/>

  <!-- ############## FT SENSOR ############### -->
  <xacro:include filename="$(find mobipick_description)/urdf/robotiq_ft_300/robotiq_ft_300.urdf.xacro" />

  <xacro:robotiq_ft_300 parent="ur5_tool0" prefix="" >
      <pose xyz="0 0 0" rpy="0 0 0" />
      <!-- <pose xyz="0 0 0.009" rpy="0 0 0" /> -->
  </xacro:robotiq_ft_300>

  <!-- ############### GRIPPER ################ -->
  <xacro:include filename="$(find mobipick_description)/urdf/robotiq_2f_140/robotiq_arg2f_140_model_macro.xacro" />

  <!-- gripper coupling (ISO 9409-1-50-4-M / Robotiq AGC-CPL-062-002_20171219) -->
  <xacro:property name="coupling_radius" value="0.0375" />
  <xacro:property name="coupling_outer_length" value="0.014" />
  <xacro:property name="coupling_inner_length" value="0.008" />
  <xacro:property name="coupling_mass" value="0.100" />

  <joint name="ft300_coupling_joint" type="fixed">
    <origin xyz="0 0 ${coupling_inner_length / 2}" rpy="0 0 ${-pi/2}" />
    <parent link="fts_toolside" />
    <child link="gripper_coupling_link" />
  </joint>

  <link name="gripper_coupling_link">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${coupling_radius}" length="${coupling_outer_length}" />
      </geometry>
      <xacro:insert_block name="material_black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${coupling_radius}" length="${coupling_outer_length}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertial radius="${coupling_radius}" length="${coupling_outer_length}" mass="${coupling_mass}">
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>
  <gazebo reference="gripper_coupling_link">
    <material>Gazebo/FlatBlack</material>
  </gazebo>

  <joint name="coupling_2f140_joint" type="fixed">
    <origin xyz="0 0 ${coupling_inner_length / 2}" rpy="0 0 0" />
    <parent link="gripper_coupling_link" />
    <child link="gripper_robotiq_arg2f_base_link" />
  </joint>

  <xacro:robotiq_arg2f_140 prefix="gripper_"/>

  <!-- ############### SENSOR MOUNT + 3D CAM  ################ -->
  <xacro:include filename="$(find mobipick_description)/urdf/sensors/gripper_cam.urdf.xacro" />

  <joint name="sensor_mount_joint" type="fixed">
    <origin xyz="0.0 0.0 -0.005" rpy="0.0 ${-pi/2} 0.0" />
    <parent link="fts_toolside" />
    <child link="sensor_mount_link" />
  </joint>

  <gripper_cam />

  <!-- ################ GAZEBO ################ -->
  <xacro:include filename="$(find mobipick_description)/urdf/mobipick/mobipick.gazebo.xacro" />
</robot>
