<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       name="mobipick">

  <xacro:arg name="robot" default="mobipick-os" />      <!-- can be "mobipick-hb" or "mobipick-os" -->
  <xacro:property name="robot" value="$(arg robot)" />  <!-- necessary because args cannot be accessed inside ${} expressions -->

  <xacro:arg name="tf_prefix" default="" />
  <xacro:property name="tf_prefix_" value="$(arg tf_prefix)" />
  <xacro:if value="${tf_prefix_ == ''}">
    <xacro:property name="prefix" value="" />
  </xacro:if>
  <xacro:unless value="${tf_prefix_ == ''}">
    <xacro:property name="prefix" value="${tf_prefix_}/" />
  </xacro:unless>

  <xacro:arg name="transmission_hw_interface" default="hardware_interface/PositionJointInterface"/>
  <xacro:arg name="kinematics_config" default="$(find mobipick_description)/config/ur5_calibration.yaml"/>  <!-- path the to the yaml with the arms calibration parameters. -->

  <!-- ############# MIR100 BASE ############## -->
  <xacro:include filename="$(find mir_description)/urdf/include/mir_100_v1.urdf.xacro" />

  <xacro:mir_100 prefix="${prefix}"/>

  <!-- ############## STRUCTURE ############### -->
  <xacro:include filename="$(find mobipick_description)/urdf/structure/mobipick_structure.urdf.xacro" />

  <joint name="${prefix}mir_struct_joint" type="fixed">
    <parent link="${prefix}surface" />
    <child link="${prefix}structure_part_down" />
    <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
  </joint>

  <xacro:if value="${robot == 'mobipick-hb'}">
    <xacro:structure prefix="${prefix}structure_" height="0.058" variant="v1" />
  </xacro:if>
  <xacro:if value="${robot == 'mobipick-os'}">
    <xacro:structure prefix="${prefix}structure_" height="0.058" variant="v2" />
  </xacro:if>

  <!-- ############### UR5 ARM ################ -->
  <xacro:include filename="$(find ur_description)/urdf/ur5.urdf.xacro" />

  <joint name="${prefix}struct_ur5_joint" type="fixed">
      <parent link="${prefix}structure_pedestal_surface" />
      <child link="${prefix}ur5_base_link" />
    <origin xyz="0.0 0.0 0.0025" rpy="0.0 0.0 0.0" />
  </joint>

  <!-- Reachable joint angles are limited by the robot structure to these
       values for the shoulder_lift_joint. It's important to restrict the joint
       angles, otherwise the planning space is discontinuous. 

       Reasons for the further limits:
       * shoulder_lift_lower_limit=-pi and elbow_joint_lower_limit=0: 
         The combination of these two limits ensures that there are no IK solutions
         which require full arm reconfigurations during picking from table height.
         These IK solutions would lead to undesirable "overhead" trajectories and also
         mess up the path simplification (planner produces a feasible plan, but path
         "simplification" introduces jumps from one configuration to the opposite one).
       * shoulder_lift_upper_limit=0.74: all values > 0.74 are in self collision
         (this limit is just an optimization)
       * elbow_joint_upper_limit=2.93: all values > 2.93 are in self collision
       * wrist_3 limits: It's nice to center the range around (pi - 0.25),
         because that is where our "home" position is and where the cables are
         least stretched. From there, wrist_3 can move pi in either direction.
       -->
  <xacro:ur5_robot prefix="${prefix}ur5_" joint_limited="true"
    shoulder_pan_lower_limit="${-pi}"   shoulder_pan_upper_limit="${pi}"
    shoulder_lift_lower_limit="${-pi}"  shoulder_lift_upper_limit="0.74"
    elbow_joint_lower_limit="0.0"       elbow_joint_upper_limit="2.93"
    wrist_1_lower_limit="${-pi}"        wrist_1_upper_limit="${pi}"
    wrist_2_lower_limit="${-pi}"        wrist_2_upper_limit="${pi}"
    wrist_3_lower_limit="${-0.25 * pi}" wrist_3_upper_limit="${1.75 * pi}"
    transmission_hw_interface="$(arg transmission_hw_interface)"
    kinematics_file="${load_yaml('$(arg kinematics_config)')}" />

  <!-- ############### CABLE GUIDE ################ -->
  <xacro:include filename="$(find mobipick_description)/urdf/cable_guide/cable_guide.urdf.xacro" />
  <xacro:cable_guide prefix="${prefix}" />

  <!-- ############## FT SENSOR ############### -->
  <xacro:include filename="$(find mobipick_description)/urdf/robotiq_ft_300/robotiq_ft_300.urdf.xacro" />

  <xacro:robotiq_ft_300 parent="${prefix}ur5_tool0" prefix="${prefix}" >
      <pose xyz="0 0 0" rpy="0 0 0" />
      <!-- <pose xyz="0 0 0.009" rpy="0 0 0" /> -->
  </xacro:robotiq_ft_300>

  <!-- ############### GRIPPER ################ -->
  <xacro:include filename="$(find mobipick_description)/urdf/robotiq_2f_140/robotiq_arg2f_140_model_macro.xacro" />

  <!-- gripper coupling (ISO 9409-1-50-4-M / Robotiq AGC-CPL-062-002_20171219) -->
  <xacro:property name="coupling_radius" value="0.0375" />
  <xacro:property name="coupling_outer_length" value="0.014" />
  <xacro:property name="coupling_inner_length" value="0.008" />
  <xacro:property name="coupling_mass" value="0.100" />

  <joint name="${prefix}ft300_coupling_joint" type="fixed">
    <origin xyz="0 0 ${coupling_inner_length / 2}" rpy="0 0 ${-pi/2}" />
    <parent link="${prefix}fts_toolside" />
    <child link="${prefix}gripper_coupling_link" />
  </joint>

  <link name="${prefix}gripper_coupling_link">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${coupling_radius}" length="${coupling_outer_length}" />
      </geometry>
      <xacro:insert_block name="material_black" />
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${coupling_radius}" length="${coupling_outer_length}" />
      </geometry>
    </collision>
    <xacro:cylinder_inertial radius="${coupling_radius}" length="${coupling_outer_length}" mass="${coupling_mass}">
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    </xacro:cylinder_inertial>
  </link>
  <gazebo reference="${prefix}gripper_coupling_link">
    <material>Gazebo/FlatBlack</material>
  </gazebo>

  <joint name="${prefix}coupling_2f140_joint" type="fixed">
    <origin xyz="0 0 ${coupling_inner_length / 2}" rpy="0 0 0" />
    <parent link="${prefix}gripper_coupling_link" />
    <child link="${prefix}gripper_robotiq_arg2f_base_link" />
  </joint>

  <xacro:robotiq_arg2f_140 prefix="${prefix}gripper_"/>

  <!-- ############### SENSOR MOUNT + 3D CAM  ################ -->
  <xacro:include filename="$(find mobipick_description)/urdf/sensors/gripper_cam.urdf.xacro" />

  <joint name="${prefix}sensor_mount_joint" type="fixed">
    <origin xyz="0.0 0.0 -0.005" rpy="0.0 ${-pi/2} 0.0" />
    <parent link="${prefix}fts_toolside" />
    <child link="${prefix}sensor_mount_link" />
  </joint>

  <xacro:gripper_cam prefix="${prefix}" />

  <!-- ############### DUAL XTION MOUNT + XTIONS ################ -->
  <xacro:if value="${robot == 'mobipick-hb'}">
    <xacro:include filename="$(find mobipick_description)/urdf/sensors/dual_xtions.urdf.xacro" />

    <joint name="${prefix}dual_xtion_mount_joint" type="fixed">
      <origin xyz="0.37 0.0 -0.02" rpy="0 0 0" />
      <parent link="${prefix}structure_pedestal" />
      <child link="${prefix}dual_xtion_mount_link" />
    </joint>

    <xacro:dual_xtions prefix="${prefix}" />
  </xacro:if>

  <!-- ################ GAZEBO ################ -->
  <xacro:include filename="$(find mobipick_description)/urdf/mobipick/mobipick.gazebo.xacro" />
  <xacro:mobipick_gazebo prefix="${prefix}" robot_namespace="" />
</robot>
