<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find mobipick_description)/urdf/common_properties.urdf.xacro" />

  <!-- variant can be one of:
       - v1: The original Mobipick in Bremen, built for the Hybr-iT project
       - v2: The newer Mobipicks: one in Osnabrueck, two in Bremen for the UPLINX project
  -->
  <xacro:macro name="structure" params="prefix height variant='v1'">
    <link name="${prefix}part_down">
      <inertial>
        <origin xyz="0 0 0.3278534031" rpy="${1.5 * pi} ${0.5 * pi} ${0.5 * pi}" />
        <mass value="3.349376" />
        <inertia
          ixx="0.432077541"
          ixy="0"
          ixz="0"
          iyy="0.369249471"
          iyz="0"
          izz="0.179676981" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/structure/visual/${variant}/part_down.stl" />
        </geometry>
        <xacro:insert_block name="material_aluminum" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/structure/collision/${variant}/part_down.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}part_down">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}part_up">
      <inertial>
        <origin xyz="0 0 0.3535849057" rpy="${1.5 * pi} ${0.5 * pi} ${0.5 * pi}" />
        <mass value="4.64704" />
        <inertia
          ixx="0.549473755"
          ixy="0"
          ixz="0"
          iyy="0.436580833"
          iyz="0"
          izz="0.245971089" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/structure/visual/${variant}/part_up.stl" />
        </geometry>
        <xacro:insert_block name="material_aluminum" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/structure/collision/${variant}/part_up.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}part_up">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}pedestal">
      <inertial>
        <origin xyz="0 0 0.1532210441" rpy="${0.5 * pi} ${0.5 * pi} 0" />
        <mass value="2.354023413" />
        <inertia
          ixx="0.049542988"
          ixy="0"
          ixz="0"
          iyy="0.042530187"
          iyz="0"
          izz="0.020198776" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/structure/visual/${variant}/pedestal.stl" />
        </geometry>
        <xacro:insert_block name="material_aluminum" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://mobipick_description/meshes/structure/collision/${variant}/pedestal.stl" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="${prefix}pedestal">
      <material>Gazebo/Grey</material>
    </gazebo>

    <link name="${prefix}pedestal_surface"/>

    <!-- <joint name="${prefix}structure_vertical_joint" type="prismatic">
      <origin xyz="0 0 ${0.04}" rpy="0 0 0" />
      <parent link="${prefix}part_down" />
      <child link="${prefix}part_up" />
      <axis xyz="0 0 1" />
      <limit effort="1000.0" lower="0.01" upper="0.25" velocity="0.01"/>
    </joint> -->
    <joint name="${prefix}structure_vertical_joint" type="fixed">
      <origin xyz="0 0 ${0.04 + height}" rpy="0 0 0" />
      <parent link="${prefix}part_down" />
      <child link="${prefix}part_up" />
    </joint>

    <joint name="${prefix}Tischaufbau_joint" type="fixed">
      <origin xyz="0 0 0.44" rpy="0 0 0" />
      <parent link="${prefix}part_up" />
      <child link="${prefix}pedestal" />
    </joint>

    <xacro:if value="${variant == 'v1'}">
      <xacro:property name="pedestal_height" value="0.2492" />
    </xacro:if>
    <xacro:if value="${variant == 'v2'}">
      <xacro:property name="pedestal_height" value="0.2291" />
    </xacro:if>

    <joint name="${prefix}Tischaufbau_base_joint" type="fixed">
      <origin xyz="0 0 ${pedestal_height}" rpy="0 0 0" />
      <parent link="${prefix}pedestal" />
      <child link="${prefix}pedestal_surface" />
    </joint>
  </xacro:macro>
</robot>
