# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  $(arg prefix)ur5_shoulder_pan_joint:
    max_position: 6.28
    min_position: -6.28
    has_velocity_limits: true
    max_velocity: 0.45
    has_acceleration_limits: true
    max_acceleration: 1.0
  $(arg prefix)ur5_shoulder_lift_joint:
    max_position: 0.69
    min_position: -3.84
    has_velocity_limits: true
    max_velocity: 0.45
    has_acceleration_limits: true
    max_acceleration: 1.0
  $(arg prefix)ur5_elbow_joint:
    max_position: 6.28
    min_position: -6.28
    has_velocity_limits: true
    max_velocity: 0.45
    has_acceleration_limits: true
    max_acceleration: 1.0
  $(arg prefix)ur5_wrist_1_joint:
    max_position: 6.28
    min_position: -6.28
    has_velocity_limits: true
    max_velocity: 0.45
    has_acceleration_limits: true
    max_acceleration: 1.0
  $(arg prefix)ur5_wrist_2_joint:
    max_position: 3.14
    min_position: -3.14
    has_velocity_limits: true
    max_velocity: 0.45
    has_acceleration_limits: true
    max_acceleration: 1.0
  $(arg prefix)ur5_wrist_3_joint:
    max_position: 6.28
    min_position: -6.28
    has_velocity_limits: true
    max_velocity: 0.45
    has_acceleration_limits: true
    max_acceleration: 1.0
  $(arg prefix)gripper_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.7
    has_acceleration_limits: false
    max_acceleration: 0
