arm:
  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  arm_prefix: ur5_   # doesn't work until https://github.com/ros-industrial/universal_robot/pull/334 is merged
