<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find mobipick_description)/urdf/common_properties.urdf.xacro" />

  <xacro:macro name="table" params="height:=0.72 width:=0.80 depth:=0.80 leg_radius:=0.02 table_top_thickness:=0.05 x:=0.0 y:=0.0 z:=0.0">
    <link name="table_top_link">

      <xacro:box_inertial x="${width}" y="${depth}" z="${table_top_thickness}" mass="10">
        <origin xyz="${x} ${y} ${z + height - table_top_thickness/2}" />
      </xacro:box_inertial>
      <visual>
        <origin xyz="${x} ${y} ${z + height - table_top_thickness/2}" />
        <geometry>
          <box size="${width} ${depth} ${table_top_thickness}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="${x} ${y} ${z + height - table_top_thickness/2}" />
        <geometry>
          <box size="${width} ${depth} ${table_top_thickness}" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="table_top_link">
      <!--<material>Gazebo/Wood</material>-->
      <mu1>1.0</mu1>
      <mu2>1.0</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
    </gazebo>

    <joint name="leg1_joint" type="fixed" >
      <parent link="table_top_link" />
      <origin xyz="${x + width/2} ${y + depth/2} ${z + height}" rpy="0 0 0" />
      <child link="leg1_link" />
    </joint>
    <link name="leg1_link">
      <xacro:cylinder_inertial radius="${leg_radius}" length="${height}" mass="2.0">
        <origin xyz="0 0 ${-height/2}" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0.0 0.0 ${-height/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${height}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${-height/2}" rpy="0.0 0.0 0.0" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${height}" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="leg1_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="leg2_joint" type="fixed" >
      <parent link="table_top_link" />
      <origin xyz="${x - width/2} ${y + depth/2} ${z + height}" rpy="0 0 0" />
      <child link="leg2_link" />
    </joint>
    <link name="leg2_link">
      <xacro:cylinder_inertial radius="${leg_radius}" length="${height}" mass="2.0">
        <origin xyz="0 0 ${-height/2}" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0.0 0.0 ${-height/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${height}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${-height/2}" rpy="0.0 0.0 0.0" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${height}" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="leg2_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="leg3_joint" type="fixed" >
      <parent link="table_top_link" />
      <origin xyz="${x + width/2} ${y - depth/2} ${z + height}" rpy="0 0 0" />
      <child link="leg3_link" />
    </joint>
    <link name="leg3_link">
      <xacro:cylinder_inertial radius="${leg_radius}" length="${height}" mass="2.0">
        <origin xyz="0 0 ${-height/2}" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0.0 0.0 ${-height/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${height}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${-height/2}" rpy="0.0 0.0 0.0" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${height}" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="leg3_link">
      <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="leg4_joint" type="fixed" >
      <parent link="table_top_link" />
      <origin xyz="${x - width/2} ${y - depth/2} ${z + height}" rpy="0 0 0" />
      <child link="leg4_link" />
    </joint>
    <link name="leg4_link">
      <xacro:cylinder_inertial radius="${leg_radius}" length="${height}" mass="2.0">
        <origin xyz="0 0 ${-height/2}" />
      </xacro:cylinder_inertial>
      <visual>
        <origin xyz="0.0 0.0 ${-height/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${height}" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${-height/2}" rpy="0.0 0.0 0.0" />
        <geometry>
          <cylinder radius="${leg_radius}" length="${height}" />
        </geometry>
      </collision>
    </link>
    <gazebo reference="leg4_link">
      <material>Gazebo/Grey</material>
    </gazebo>
    <gazebo>
      <static>true</static>
    </gazebo>
  </xacro:macro>
</robot>
